version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: smart_commerce_llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/models
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    entrypoint: ["/bin/sh", "/models/ollama-entrypoint.sh"]
    networks:
      - backend

volumes:
  ollama_data:

networks:
  backend:
    driver: bridge