"""init_schema

Revision ID: 586af5823cb4
Revises: 
Create Date: 2026-08-01 10:11:28.613867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '586af5823cb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('competitor_prices')
    # op.drop_table('demographics')
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_analyses_report_id'), table_name='analyses')
    op.alter_column('innovations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_innovations_analysis_id'), table_name='innovations')
    op.alter_column('mentor_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mentor_messages_analysis_id'), table_name='mentor_messages')
    op.alter_column('sales_items', 'qty_sold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sales_items', 'remaining_stock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_sales_items_report_id'), table_name='sales_items')
    op.alter_column('sales_reports', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('simulations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_simulations_innovation_id'), table_name='simulations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_simulations_innovation_id'), 'simulations', ['innovation_id'], unique=False)
    op.alter_column('simulations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sales_reports', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_sales_items_report_id'), 'sales_items', ['report_id'], unique=False)
    op.alter_column('sales_items', 'remaining_stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sales_items', 'qty_sold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_mentor_messages_analysis_id'), 'mentor_messages', ['analysis_id'], unique=False)
    op.alter_column('mentor_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_innovations_analysis_id'), 'innovations', ['analysis_id'], unique=False)
    op.alter_column('innovations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_analyses_report_id'), 'analyses', ['report_id'], unique=False)
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('demographics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('segment_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('age_group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('demographics_pkey'))
    )
    op.create_table('competitor_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('competitor_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.CheckConstraint('price > 0::numeric', name=op.f('competitor_prices_price_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('competitor_prices_pkey'))
    )
    # ### end Alembic commands ###
