"""add demographics, foot_traffic, and competitor_prices to market models

Revision ID: 960bedd0055a
Revises: 586af5823cb4
Create Date: 2026-08-02 19:39:20.640408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960bedd0055a'
down_revision: Union[str, Sequence[str], None] = '586af5823cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_name', sa.String(length=100), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True, comment='Harga rata-rata produk kompetitor (IDR)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_prices_competitor_name'), 'competitor_prices', ['competitor_name'], unique=False)
    op.create_table('demographics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_area', sa.String(length=100), nullable=True),
    sa.Column('population_density', sa.Integer(), nullable=True, comment='Kepadatan per km persegi'),
    sa.Column('dominant_age_group', sa.String(length=50), nullable=True),
    sa.Column('average_income', sa.Float(), nullable=True, comment='Rata-rata pendapatan (IDR)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographics_location_area'), 'demographics', ['location_area'], unique=False)
    op.create_table('foot_traffic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_area', sa.String(length=100), nullable=True),
    sa.Column('time_period', sa.String(length=50), nullable=True, comment='Misal: Pagi, Siang, Sore, Malam'),
    sa.Column('traffic_volume', sa.Integer(), nullable=True, comment='Estimasi jumlah orang lewat per jam'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foot_traffic_location_area'), 'foot_traffic', ['location_area'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foot_traffic_location_area'), table_name='foot_traffic')
    op.drop_table('foot_traffic')
    op.drop_index(op.f('ix_demographics_location_area'), table_name='demographics')
    op.drop_table('demographics')
    op.drop_index(op.f('ix_competitor_prices_competitor_name'), table_name='competitor_prices')
    op.drop_table('competitor_prices')
    # ### end Alembic commands ###
