"""add_full_domain_models

Revision ID: a7a953e92c42
Revises: 960bedd0055a
Create Date: 2026-08-02 22:41:10.355269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7a953e92c42'
down_revision: Union[str, Sequence[str], None] = '960bedd0055a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitor_prices', 'average_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Harga rata-rata produk kompetitor (IDR)',
               existing_nullable=True)
    op.alter_column('competitor_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('demographics', 'population_density',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Kepadatan per km persegi',
               existing_nullable=True)
    op.alter_column('demographics', 'average_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Rata-rata pendapatan (IDR)',
               existing_nullable=True)
    op.alter_column('demographics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('foot_traffic', 'time_period',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Misal: Pagi, Siang, Sore, Malam',
               existing_nullable=True)
    op.alter_column('foot_traffic', 'traffic_volume',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Estimasi jumlah orang lewat per jam',
               existing_nullable=True)
    op.alter_column('foot_traffic', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foot_traffic', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('foot_traffic', 'traffic_volume',
               existing_type=sa.INTEGER(),
               comment='Estimasi jumlah orang lewat per jam',
               existing_nullable=True)
    op.alter_column('foot_traffic', 'time_period',
               existing_type=sa.VARCHAR(length=50),
               comment='Misal: Pagi, Siang, Sore, Malam',
               existing_nullable=True)
    op.alter_column('demographics', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('demographics', 'average_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Rata-rata pendapatan (IDR)',
               existing_nullable=True)
    op.alter_column('demographics', 'population_density',
               existing_type=sa.INTEGER(),
               comment='Kepadatan per km persegi',
               existing_nullable=True)
    op.alter_column('competitor_prices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('competitor_prices', 'average_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Harga rata-rata produk kompetitor (IDR)',
               existing_nullable=True)
    # ### end Alembic commands ###
